from __future__ import annotations

from datetime import datetime, timezone

from pydantic import BaseModel, Field

from agent_framework.models.message import Message


class SessionState(BaseModel):
    """Unique holder of current run's message history.

    None/empty convention (v2.5.2 §23):
    - messages: always [], never None — empty session has no messages
    - session_id / run_id: "" means not yet assigned (transient init state)
    - started_at / last_updated_at: always populated (non-optional)

    Write-port contract:
    - Only RunStateController.project_iteration_to_session() calls append_message()
    - No other module may call append_message() during a run
    - clear() is only used between runs or in tests

    Streaming boundary (v2.6.1 §34):
    - LLMResponseChunk / ModelChunk MUST NOT be written here.
    - Only final merged ModelResponse (via MessageProjector) enters messages.
    - Interrupted streams produce NO assistant message — only audit record.
    """

    session_id: str = ""
    run_id: str = ""
    messages: list[Message] = Field(default_factory=list)
    started_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    last_updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc)
    )

    def append_message(self, msg: Message) -> None:
        self.messages.append(msg)
        self.last_updated_at = datetime.now(timezone.utc)

    def get_messages(self) -> list[Message]:
        return list(self.messages)

    def clear(self) -> None:
        self.messages.clear()
        self.last_updated_at = datetime.now(timezone.utc)


class SessionSnapshot:
    """Immutable read-only snapshot of SessionState for context layer (v2.6.4 §45).

    The context layer (ContextSourceProvider, ContextEngineer) MUST NOT consume
    mutable SessionState directly. Instead, RunStateController produces a
    SessionSnapshot which is frozen at creation time.

    Invariants:
    - Messages list is a shallow copy — immutable once created
    - snapshot_version is monotonically increasing per session
    - Same context build MUST use a single snapshot (no mid-build refresh)
    - ContextSourceProvider/ContextEngineer MUST NOT hold SessionState references

    Prohibited:
    - Passing mutable SessionState to context layer
    - Reading messages from a SessionState that may change mid-build
    - Sharing SessionState memory object between context layer and write-port
    """

    __slots__ = (
        "run_session_id", "messages", "snapshot_version", "created_at",
    )

    def __init__(self, session_state: SessionState) -> None:
        self.run_session_id = session_state.session_id
        self.messages: list[Message] = list(session_state.messages)
        self.snapshot_version = len(session_state.messages)
        self.created_at = session_state.last_updated_at

    def get_messages(self) -> list[Message]:
        """Return messages (already a copy from construction)."""
        return list(self.messages)


class RunCheckpoint(BaseModel):
    """Placeholder for future checkpoint/resume support (v2.6.5 §48).

    Current version does NOT support generic run-level resume.
    Interrupted runs are terminated; continuation requires a new run.

    Stance:
    - SessionState, iteration_history, EventBus events, StructLogger logs,
      and streaming output caches are NOT valid resume truth sources.
    - "Continue conversation" in the UI must map to a NEW run, not resume.
    - Resume support requires formal checkpoint with the fields below.

    Until this class is promoted from placeholder to active use:
    - No code may claim to support run resume
    - No code may reconstruct AgentState from logs or events
    - No code may rebuild execution pointers from SessionState.messages
    - No code may derive active_handles/active_skill from event streams

    Minimum checkpoint consistency unit (for future implementation):
    - Agent state snapshot at checkpoint time
    - Session snapshot reference
    - Transaction group index reference
    - Artifact index reference
    - External side-effect fence (what was committed vs pending)
    """

    checkpoint_id: str = ""
    run_id: str = ""
    run_session_id: str = ""
    agent_state_snapshot_ref: str = ""
    session_snapshot_ref: str = ""
    transaction_index_ref: str = ""
    artifact_index_ref: str = ""
    checkpoint_version: int = 0
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class RuntimeIdentityBundle(BaseModel):
    """Separates external (integration) IDs from internal (kernel) IDs (v2.6.3 §42).

    ID attribution rules:
    - Internal IDs (run_id, run_session_id) are generated by the kernel.
    - External IDs (external_session_id, request_id, user_id) are provided
      by the integration layer and may be None for standalone runs.
    - Memory/audit/artifact/transaction associations MUST use internal IDs.
    - Sub-agents MUST NOT reuse parent external IDs as their own primary IDs.
    - The kernel MUST support running without any external IDs.

    ID attribution table:
    ┌─────────────────────┬─────────────┬──────────────────────────────┐
    │ ID                  │ Generated by│ Purpose                      │
    ├─────────────────────┼─────────────┼──────────────────────────────┤
    │ external_session_id │ Integration │ User-facing session tracking  │
    │ request_id          │ Integration │ Single request tracing        │
    │ user_id             │ Integration │ Auth identity                 │
    │ run_id              │ Kernel      │ Runtime execution instance    │
    │ run_session_id      │ Kernel      │ Session state container       │
    │ iteration_id        │ Kernel      │ Single iteration identifier   │
    │ transaction_group_id│ Kernel      │ Tool transaction group        │
    │ subagent_task_id    │ Kernel      │ Scheduler task tracking       │
    │ child_run_id        │ Kernel      │ Sub-agent runtime instance    │
    │ artifact_id         │ Kernel      │ Artifact stable reference     │
    │ audit_ref           │ Kernel      │ Audit record reference        │
    └─────────────────────┴─────────────┴──────────────────────────────┘

    Prohibited:
    - Using external_session_id as run_id
    - Using run_id to represent a UI long-session
    - Same field meaning different ID types in different layers
    - Sub-agent inheriting parent's full external IDs as primary
    """

    # Internal (kernel-generated)
    run_id: str = ""
    run_session_id: str = ""
    # External (integration-provided, optional)
    external_session_id: str | None = None
    request_id: str | None = None
    user_id: str | None = None
    # Parent reference (for sub-agents)
    parent_run_id: str | None = None
