from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

from agent_framework.models.message import Message


class ToolTransactionGroup(BaseModel):
    """An atomic group of messages that cannot be split during context trimming.

    Examples:
    - An assistant message with tool_calls + all corresponding tool result messages
    - A spawn_agent request + its return result
    """

    group_id: str = ""
    group_type: Literal["TOOL_BATCH", "SUBAGENT_BATCH", "PLAIN_MESSAGES"] = (
        "PLAIN_MESSAGES"
    )
    messages: list[Message] = Field(default_factory=list)
    token_estimate: int = 0
    protected: bool = False


class TransactionGroupIndex(BaseModel):
    """Pre-computed index of tool transaction groups (v2.6.3 §40).

    Generated by MessageProjector/RunStateController at commit time.
    ContextSourceProvider MUST consume this index instead of
    reconstructing groups from linear session messages.

    Invariants:
    - group_id is stable once assigned (never regenerated)
    - A message belongs to at most one group
    - Missing metadata → group is "not safely trimmable" (degraded, not rebuilt)
    - ContextSourceProvider/ContextEngineer may NOT generate new group IDs
    """

    groups_by_id: dict[str, ToolTransactionGroup] = Field(default_factory=dict)
    groups_by_iteration: dict[str, list[str]] = Field(default_factory=dict)
    message_to_group: dict[str, str] = Field(default_factory=dict)
